# Generated by Django 5.0.7 on 2024-07-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("bio", models.TextField(blank=True)),
                ("skills", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=100)),
                ("job_title", models.CharField(max_length=100)),
                ("years_experience", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
